on:
  push:
    branches:
      - master




jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: "Login to docker hub"
        run: docker login --username ${{secrets.dacker username}} --password ${{secrets.docker token}}
      
      - name: "building docker image"
        run: docker build -t ${{secrets.dacker username}}/myimg .

      - name: "Pushing to docker hub"
        run: docker push ${{secrets.dacker username}}/myimg


        
